using System;
using UnityEngine;
using HarmonyLib;
using Il2CppInterop.Runtime;
using Il2CppDialogOption = EvidenceWitness.DialogOption;
using Il2CppOptionList = Il2CppSystem.Collections.Generic.List<EvidenceWitness.DialogOption>;

namespace SODMotives
{
    // V2 proof-of-concept: add a custom player interrogation question whose answer
    // is generated by the mod at runtime and spoken by the interviewed NPC.
    //
    // Mechanism (verified, dependency-free):
    //   - a DialogPreset (specialCase = none) we build at runtime
    //   - injected into the interview menu via a postfix on EvidenceWitness.GetDialogOptions
    //   - answered via a prefix on DialogController.ExecuteDialog, which composes a
    //     string, bakes it into a runtime DDS block+message, and Speaks it.
    internal static class Interrogation
    {
        internal static bool Enable = true;

        private static bool _inited;
        private static DialogPreset _preset;
        private const string QuestionMsgId = "MOD_Motives_Q_WhatSeen";
        private const string QuestionText = "(Motives) Have you seen anything unusual lately?";
        private static int _answerCounter;

        // Build the question preset + inject its label DDS once the game/Toolbox is ready.
        internal static void EnsureInit()
        {
            if (_inited) return;
            try
            {
                var tb = Toolbox.Instance;
                if (tb == null || tb.allDDSMessages == null) return; // not ready yet; try again next call
                _inited = true;

                InjectMessage(QuestionMsgId, QuestionText);

                _preset = ScriptableObject.CreateInstance<DialogPreset>();
                _preset.name = "MOD_MotivesQuestion";
                _preset.msgID = QuestionMsgId;
                _preset.specialCase = DialogPreset.SpecialCase.none;
                _preset.defaultOption = true;
                _preset.tiedToKey = Evidence.DataKey.name;
                _preset.ranking = 50;
                _preset.cost = 0;
                _preset.baseChance = 1f;
                _preset.useSuccessTest = false;
                _preset.removeAfterSaying = false;
                _preset.dailyReplenish = true;
                _preset.preceedingSyntax = "";
                _preset.followingSyntax = "";
                try { _preset.responses = new Il2CppSystem.Collections.Generic.List<AIActionPreset.AISpeechPreset>(); } catch { }

                MotivesPlugin.Log.LogInfo("[SODMotives][interro] question preset built + label injected.");
            }
            catch (Exception e) { MotivesPlugin.Log.LogWarning($"[SODMotives][interro] init error: {e}"); }
        }

        // Bake a literal string into a runtime DDS block+message so it can be Spoken / shown.
        private static void InjectMessage(string msgId, string text)
        {
            try
            {
                var tb = Toolbox.Instance;
                string blockId = msgId + "_blk";

                var block = new DDSSaveClasses.DDSBlockSave();
                block.name = text;
                block.id = blockId;
                tb.allDDSBlocks[blockId] = block;

                var cond = new DDSSaveClasses.DDSBlockCondition();
                cond.blockID = blockId;
                cond.instanceID = msgId + "_inst";
                cond.alwaysDisplay = true;
                cond.group = 0;

                var msg = new DDSSaveClasses.DDSMessageSave();
                msg.name = msgId;
                msg.id = msgId;
                msg.blocks = new Il2CppSystem.Collections.Generic.List<DDSSaveClasses.DDSBlockCondition>();
                msg.blocks.Add(cond);
                tb.allDDSMessages[msgId] = msg;
            }
            catch (Exception e) { MotivesPlugin.Log.LogWarning($"[SODMotives][interro] InjectMessage('{msgId}') error: {e}"); }
        }

        internal static bool IsOurPreset(DialogPreset p)
        {
            try { return p != null && p.msgID == QuestionMsgId; } catch { return false; }
        }

        // Compose + speak the answer through the interviewed NPC.
        internal static void Answer(Human npc)
        {
            try
            {
                if (npc == null || npc.speechController == null) { MotivesPlugin.Log.LogInfo("[SODMotives][interro] no npc/speech."); return; }
                string name = "someone"; try { name = npc.citizenName; } catch { }
                string text = $"(Motives) I'm {name}. Nothing unusual comes to mind right now.";
                string ansId = "MOD_Motives_Ans_" + (_answerCounter++);
                InjectMessage(ansId, text);
                MotivesPlugin.Log.LogInfo($"[SODMotives][interro] {name} answering -> \"{text}\"");
                npc.speechController.Speak(ansId);
            }
            catch (Exception e) { MotivesPlugin.Log.LogWarning($"[SODMotives][interro] Answer error: {e}"); }
        }

        internal static void AddOptionIfMissing(Il2CppOptionList list)
        {
            if (!Enable) return;
            EnsureInit();
            if (_preset == null || list == null) return;
            try
            {
                for (int i = 0; i < list.Count; i++)
                {
                    var o = list[i];
                    if (o != null && IsOurPreset(o.preset)) return; // already present
                }
                var opt = new Il2CppDialogOption();
                opt.preset = _preset;
                list.Add(opt);
            }
            catch (Exception e) { MotivesPlugin.Log.LogWarning($"[SODMotives][interro] AddOption error: {e.Message}"); }
        }
    }

    // Inject our question into every interview option list.
    [HarmonyPatch(typeof(EvidenceWitness), nameof(EvidenceWitness.GetDialogOptions), new Type[] { typeof(Evidence.DataKey) })]
    internal static class Patch_GetDialogOptions_Single
    {
        static void Postfix(Il2CppOptionList __result) => Interrogation.AddOptionIfMissing(__result);
    }

    [HarmonyPatch(typeof(EvidenceWitness), nameof(EvidenceWitness.GetDialogOptions), new Type[] { typeof(Il2CppSystem.Collections.Generic.List<Evidence.DataKey>) })]
    internal static class Patch_GetDialogOptions_Multi
    {
        static void Postfix(Il2CppOptionList __result) => Interrogation.AddOptionIfMissing(__result);
    }

    // Answer our question ourselves (skip vanilla handling for it).
    [HarmonyPatch(typeof(DialogController), nameof(DialogController.ExecuteDialog))]
    internal static class Patch_ExecuteDialog
    {
        static bool Prefix(Il2CppDialogOption dialog, Interactable saysTo)
        {
            try
            {
                if (dialog == null || !Interrogation.IsOurPreset(dialog.preset)) return true; // vanilla
                Human npc = saysTo != null ? saysTo.TryCast<Human>() : null;
                Interrogation.Answer(npc);
                return false; // handled
            }
            catch (Exception e) { MotivesPlugin.Log.LogWarning($"[SODMotives][interro] ExecuteDialog prefix error: {e.Message}"); return true; }
        }
    }
}
